FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json yarn.lock ./
COPY prisma/schema.prisma ./prisma/

RUN yarn install 
RUN yarn prisma generate

COPY . .

EXPOSE 3000

CMD ["yarn", "start:dev"]
