version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      TZ: Asia/Seoul
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
  redis:
    image: redis:6.2.5
    restart: always
    ports:
      - 6379:6379
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/conf/redis.conf
      - ./redis/data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.dev
